/**
 * React component for Schematex diagrams.
 *
 * @example
 * ```tsx
 * import { SchematexDiagram } from 'schematex/react';
 *
 * <SchematexDiagram
 *   dsl="genogram\n  alice [female]"
 *   theme="monochrome"
 *   className="my-diagram"
 * />
 * ```
 */

import { useMemo } from "react";
import { render, type SchematexConfig } from "./core/api";

export interface SchematexDiagramProps {
  /** DSL text to render */
  dsl: string;
  /** Diagram type override (auto-detected from DSL if omitted) */
  type?: SchematexConfig["type"];
  /** Theme name: 'default' | 'monochrome' | 'dark' */
  theme?: string;
  /** Font family override */
  fontFamily?: string;
  /** Canvas padding in px */
  padding?: number;
  /** className for the wrapper div */
  className?: string;
  /** Inline style for the wrapper div */
  style?: React.CSSProperties;
  /** Called when render throws a parse/layout error */
  onError?: (error: Error) => void;
}

export function SchematexDiagram({
  dsl,
  type,
  theme,
  fontFamily,
  padding,
  className,
  style,
  onError,
}: SchematexDiagramProps) {
  const svg = useMemo(() => {
    try {
      return render(dsl, { type, theme, fontFamily, padding });
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      onError?.(e);
      return null;
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dsl, type, theme, fontFamily, padding]);

  return (
    <div
      className={className}
      style={style}
      // SVG is generated by our own renderer — safe
      dangerouslySetInnerHTML={{ __html: svg ?? "" }}
    />
  );
}
