/**
 * React component for Schematex diagrams.
 *
 * @example
 * ```tsx
 * import { SchematexDiagram } from 'schematex/react';
 *
 * <SchematexDiagram
 *   dsl="genogram\n  alice [female]"
 *   theme="monochrome"
 *   className="my-diagram"
 * />
 * ```
 */

import { useMemo } from "react";
import { renderResult, type SchematexConfig } from "./core/api";

export interface SchematexDiagramProps {
  /** DSL text to render */
  dsl: string;
  /** Diagram type override (auto-detected from DSL if omitted) */
  type?: SchematexConfig["type"];
  /** Theme name: 'default' | 'monochrome' | 'dark' */
  theme?: string;
  /** Font family override */
  fontFamily?: string;
  /** Canvas padding in px */
  padding?: number;
  /** className for the wrapper div */
  className?: string;
  /** Inline style for the wrapper div */
  style?: React.CSSProperties;
  /** Called when strict parsing/layout fails before the preview SVG fallback. */
  onError?: (error: Error) => void;
}

export function SchematexDiagram({
  dsl,
  type,
  theme,
  fontFamily,
  padding,
  className,
  style,
  onError,
}: SchematexDiagramProps) {
  const svg = useMemo(() => {
    const result = renderResult(dsl, { type, theme, fontFamily, padding });
    if (!result.ok) {
      onError?.(new Error(result.diagnostics[0]?.message ?? "Schematex render failed"));
    }
    return result.svg;
    // onError excluded — a fresh callback shouldn't bust the memo.
  }, [dsl, type, theme, fontFamily, padding]);

  return (
    <div
      className={className}
      style={style}
      // SVG is generated by our own renderer — safe
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
